"""initial schema

Revision ID: d29e23caab81
Revises: 
Create Date: 2026-08-01 02:08:42.149939
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('algorithm', sa.String(length=64), nullable=False),
    sa.Column('feature_set_version', sa.String(length=32), nullable=False),
    sa.Column('as_of_policy', sa.String(length=24), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('step_days', sa.Integer(), nullable=False),
    sa.Column('validation_days', sa.Integer(), nullable=False),
    sa.Column('min_train_rows', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('git_sha', sa.String(length=64), nullable=True),
    sa.Column('n_games', sa.Integer(), nullable=False),
    sa.Column('n_steps', sa.Integer(), nullable=False),
    sa.Column('n_steps_skipped', sa.Integer(), nullable=False),
    sa.Column('sanity_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ballparks',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('elevation_ft', sa.Integer(), nullable=True),
    sa.Column('azimuth_angle', sa.Float(), nullable=True),
    sa.Column('roof_type', sa.Text(), nullable=True),
    sa.Column('turf_type', sa.Text(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('lf_line', sa.Integer(), nullable=True),
    sa.Column('lf_center', sa.Integer(), nullable=True),
    sa.Column('center', sa.Integer(), nullable=True),
    sa.Column('rf_center', sa.Integer(), nullable=True),
    sa.Column('rf_line', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('source_name', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('knowledge_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ballparks_knowledge_time'), 'ballparks', ['knowledge_time'], unique=False)
    op.create_table('data_source_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('freshness', sa.String(length=16), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('records_last_run', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("freshness IN ('FRESH','AGING','STALE','UNAVAILABLE')", name='ck_dss_freshness'),
    sa.CheckConstraint("status IN ('OK','DEGRADED','UNAVAILABLE')", name='ck_dss_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name', 'category', name='uq_source_category')
    )
    op.create_table('job_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('job_name', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rows_written', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("status IN ('RUNNING','SUCCESS','FAILED')", name='ck_job_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_runs_name_started', 'job_runs', ['job_name', 'started_at'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('algorithm', sa.String(length=64), nullable=False),
    sa.Column('feature_set_version', sa.String(length=32), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('train_start_date', sa.Date(), nullable=True),
    sa.Column('train_end_date', sa.Date(), nullable=True),
    sa.Column('train_rows', sa.Integer(), nullable=True),
    sa.Column('hyperparameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('calibration_method', sa.String(length=32), nullable=True),
    sa.Column('calibration_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feature_names', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('artifact_path', sa.Text(), nullable=True),
    sa.Column('artifact_sha256', sa.String(length=64), nullable=True),
    sa.Column('git_sha', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_model_version')
    )
    op.create_index('uq_model_version_active', 'model_versions', ['name'], unique=True, postgresql_where=sa.text('is_active IS true'))
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('primary_position', sa.String(length=8), nullable=True),
    sa.Column('position_type', sa.Text(), nullable=True),
    sa.Column('bat_side', sa.String(length=1), nullable=True),
    sa.Column('pitch_hand', sa.String(length=1), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('mlb_debut_date', sa.Date(), nullable=True),
    sa.Column('height_in', sa.Integer(), nullable=True),
    sa.Column('weight_lb', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('source_name', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('knowledge_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_knowledge_time'), 'players', ['knowledge_time'], unique=False)
    op.create_table('raw_source_payloads',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_name', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('request_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('knowledge_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name', 'endpoint', 'content_hash', name='uq_raw_payload')
    )
    op.create_index('ix_raw_retrieved', 'raw_source_payloads', ['retrieved_at'], unique=False)
    op.create_table('backtest_results',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=True),
    sa.Column('slice_type', sa.String(length=32), nullable=False),
    sa.Column('slice_key', sa.String(length=64), nullable=False),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('n_games', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Numeric(precision=7, scale=5), nullable=True),
    sa.Column('log_loss', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('brier_score', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('calibration_error', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('max_calibration_error', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('roc_auc', sa.Numeric(precision=7, scale=5), nullable=True),
    sa.Column('roi', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('clv', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'slice_type', 'slice_key', name='uq_backtest_slice')
    )
    op.create_index('ix_btr_run_slice', 'backtest_results', ['run_id', 'slice_type'], unique=False)
    op.create_table('park_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('factor_type', sa.String(length=16), nullable=False),
    sa.Column('handedness', sa.String(length=1), nullable=True),
    sa.Column('value', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('sample_games', sa.Integer(), nullable=True),
    sa.Column('method', sa.Text(), nullable=True),
    sa.Column('is_estimated', sa.Boolean(), nullable=False),
    sa.Column('source_name', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('knowledge_time', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("factor_type IN ('runs','hr','hits','doubles','triples','k','bb')", name='ck_park_factor_type'),
    sa.ForeignKeyConstraint(['venue_id'], ['ballparks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'season', 'factor_type', 'handedness', name='uq_park_factor')
    )
    op.create_index(op.f('ix_park_factors_knowledge_time'), 'park_factors', ['knowledge_time'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('abbreviation', sa.String(length=8), nullable=False),
    sa.Column('team_name', sa.Text(), nullable=True),
    sa.Column('location_name', sa.Text(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('league_name', sa.Text(), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('division_name', sa.Text(), nullable=True),
    sa.Column('home_venue_id', sa.Integer(), nullable=True),
    sa.Column('first_year_of_play', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('source_name', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('knowledge_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['home_venue_id'], ['ballparks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_knowledge_time'), 'teams', ['knowledge_time'], unique=False)
    op.create_table('games',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('game_guid', sa.Text(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('game_type', sa.String(length=4), nullable=False),
    sa.Column('game_date_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('official_date', sa.Date(), nullable=False),
    sa.Column('status_abstract', sa.String(length=16), nullable=True),
    sa.Column('status_detailed', sa.Text(), nullable=True),
    sa.Column('status_code', sa.String(length=8), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('day_night', sa.String(length=8), nullable=True),
    sa.Column('doubleheader', sa.String(length=1), nullable=True),
    sa.Column('game_number', sa.Integer(), nullable=True),
    sa.Column('series_game_number', sa.Integer(), nullable=True),
    sa.Column('games_in_series', sa.Integer(), nullable=True),
    sa.Column('scheduled_innings', sa.Integer(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('home_win', sa.Boolean(), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('innings_played', sa.Integer(), nullable=True),
    sa.Column('game_end_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('home_probable_pitcher_id', sa.Integer(), nullable=True),
    sa.Column('away_probable_pitcher_id', sa.Integer(), nullable=True),
    sa.Column('probable_pitchers_confirmed', sa.Boolean(), nullable=False),
    sa.Column('home_record_wins', sa.Integer(), nullable=True),
    sa.Column('home_record_losses', sa.Integer(), nullable=True),
    sa.Column('away_record_wins', sa.Integer(), nullable=True),
    sa.Column('away_record_losses', sa.Integer(), nullable=True),
    sa.Column('weather_condition', sa.Text(), nullable=True),
    sa.Column('weather_temp_f', sa.Integer(), nullable=True),
    sa.Column('weather_wind', sa.Text(), nullable=True),
    sa.Column('source_name', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('knowledge_time', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(home_win IS NULL) OR (is_final AND home_score IS NOT NULL AND away_score IS NOT NULL)', name='ck_games_label_requires_final'),
    sa.ForeignKeyConstraint(['away_probable_pitcher_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_probable_pitcher_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['ballparks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_games_away_date', 'games', ['away_team_id', 'game_date_utc'], unique=False)
    op.create_index('ix_games_final_date', 'games', ['is_final', 'game_date_utc'], unique=False)
    op.create_index('ix_games_home_date', 'games', ['home_team_id', 'game_date_utc'], unique=False)
    op.create_index(op.f('ix_games_knowledge_time'), 'games', ['knowledge_time'], unique=False)
    op.create_index('ix_games_official_date', 'games', ['official_date'], unique=False)
    op.create_index('ix_games_season_type', 'games', ['season', 'game_type'], unique=False)
    op.create_table('injuries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('body_part', sa.Text(), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_return', sa.Date(), nullable=True),
    sa.Column('source_name', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('knowledge_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_injuries_knowledge_time'), 'injuries', ['knowledge_time'], unique=False)
    op.create_index('ix_injuries_player_effective', 'injuries', ['player_id', 'effective_from'], unique=False)
    op.create_table('rosters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('roster_type', sa.Text(), nullable=True),
    sa.Column('jersey_number', sa.String(length=8), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_name', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('knowledge_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rosters_knowledge_time'), 'rosters', ['knowledge_time'], unique=False)
    op.create_index('ix_rosters_player', 'rosters', ['player_id'], unique=False)
    op.create_index('ix_rosters_team_season', 'rosters', ['team_id', 'season'], unique=False)
    op.create_table('backtest_predictions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('predicted_home_win_prob', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('actual_home_win', sa.Boolean(), nullable=False),
    sa.Column('train_end_date', sa.Date(), nullable=False),
    sa.Column('n_train_rows', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('lineup_confirmed', sa.Boolean(), nullable=False),
    sa.Column('starter_quality_index', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'game_id', name='uq_backtest_pred')
    )
    op.create_index('ix_btp_run', 'backtest_predictions', ['run_id'], unique=False)
    op.create_table('bullpen_availability',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('pitcher_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('availability', sa.String(length=16), nullable=False),
    sa.Column('pitches_last_1d', sa.Integer(), nullable=True),
    sa.Column('pitches_last_2d', sa.Integer(), nullable=True),
    sa.Column('pitches_last_3d', sa.Integer(), nullable=True),
    sa.Column('appearances_last_3d', sa.Integer(), nullable=True),
    sa.Column('appearances_last_7d', sa.Integer(), nullable=True),
    sa.Column('consecutive_days_pitched', sa.Integer(), nullable=True),
    sa.Column('is_closer', sa.Boolean(), nullable=True),
    sa.Column('is_setup', sa.Boolean(), nullable=True),
    sa.Column('throws', sa.String(length=1), nullable=True),
    sa.Column('expected_role', sa.Text(), nullable=True),
    sa.Column('source_name', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('knowledge_time', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("availability IN ('AVAILABLE','LIMITED','UNAVAILABLE','UNKNOWN')", name='ck_bullpen_availability'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['pitcher_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'team_id', 'pitcher_id', 'as_of', name='uq_bullpen_avail')
    )
    op.create_index(op.f('ix_bullpen_availability_knowledge_time'), 'bullpen_availability', ['knowledge_time'], unique=False)
    op.create_table('game_officials',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('official_type', sa.String(length=32), nullable=False),
    sa.Column('official_id', sa.Integer(), nullable=True),
    sa.Column('official_name', sa.Text(), nullable=True),
    sa.Column('source_name', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('knowledge_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'official_type', name='uq_game_official')
    )
    op.create_index(op.f('ix_game_officials_knowledge_time'), 'game_officials', ['knowledge_time'], unique=False)
    op.create_table('lineups',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('batting_order', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=8), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('lineup_status', sa.String(length=16), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_name', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('knowledge_time', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("lineup_status IN ('CONFIRMED','PROJECTED','UNAVAILABLE')", name='ck_lineup_status'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'team_id', 'batting_order', 'knowledge_time', name='uq_lineup_snapshot')
    )
    op.create_index('ix_lineups_game_team', 'lineups', ['game_id', 'team_id'], unique=False)
    op.create_index(op.f('ix_lineups_knowledge_time'), 'lineups', ['knowledge_time'], unique=False)
    op.create_table('model_features',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('team_side', sa.String(length=1), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('feature_set_version', sa.String(length=32), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sample_sizes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('estimated_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_features', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('completeness', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("team_side IN ('H','A')", name='ck_mf_side'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'team_side', 'as_of', 'feature_set_version', name='uq_model_feature')
    )
    op.create_index('ix_mf_features', 'model_features', ['features'], unique=False, postgresql_using='gin')
    op.create_index('ix_mf_game', 'model_features', ['game_id'], unique=False)
    op.create_table('odds_snapshots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('book', sa.Text(), nullable=False),
    sa.Column('market', sa.String(length=32), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('home_price', sa.Integer(), nullable=True),
    sa.Column('away_price', sa.Integer(), nullable=True),
    sa.Column('home_implied_prob', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('away_implied_prob', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('home_novig_prob', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('away_novig_prob', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('total_line', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('is_closing', sa.Boolean(), nullable=False),
    sa.Column('source_name', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('knowledge_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_odds_game_time', 'odds_snapshots', ['game_id', 'snapshot_at'], unique=False)
    op.create_index(op.f('ix_odds_snapshots_knowledge_time'), 'odds_snapshots', ['knowledge_time'], unique=False)
    op.create_table('pitches',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('at_bat_index', sa.Integer(), nullable=True),
    sa.Column('pitch_number', sa.Integer(), nullable=True),
    sa.Column('pitcher_id', sa.Integer(), nullable=False),
    sa.Column('batter_id', sa.Integer(), nullable=False),
    sa.Column('inning', sa.Integer(), nullable=True),
    sa.Column('is_top', sa.Boolean(), nullable=True),
    sa.Column('balls', sa.Integer(), nullable=True),
    sa.Column('strikes', sa.Integer(), nullable=True),
    sa.Column('outs', sa.Integer(), nullable=True),
    sa.Column('pitch_type', sa.String(length=8), nullable=True),
    sa.Column('release_speed', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('spin_rate', sa.Integer(), nullable=True),
    sa.Column('pfx_x', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('pfx_z', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('plate_x', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('plate_z', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('release_extension', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('zone', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('call', sa.Text(), nullable=True),
    sa.Column('source_name', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('knowledge_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batter_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['pitcher_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pitches_batter', 'pitches', ['batter_id', 'game_id'], unique=False)
    op.create_index('ix_pitches_game', 'pitches', ['game_id'], unique=False)
    op.create_index(op.f('ix_pitches_knowledge_time'), 'pitches', ['knowledge_time'], unique=False)
    op.create_index('ix_pitches_pitcher', 'pitches', ['pitcher_id', 'game_id'], unique=False)
    op.create_table('player_game_stats',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('opponent_team_id', sa.Integer(), nullable=False),
    sa.Column('game_date_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=8), nullable=False),
    sa.Column('batting_order', sa.Integer(), nullable=True),
    sa.Column('batting_order_slot', sa.Integer(), nullable=True),
    sa.Column('is_starter', sa.Boolean(), nullable=False),
    sa.Column('position', sa.String(length=8), nullable=True),
    sa.Column('pa', sa.Integer(), nullable=True),
    sa.Column('ab', sa.Integer(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('doubles', sa.Integer(), nullable=True),
    sa.Column('triples', sa.Integer(), nullable=True),
    sa.Column('home_runs', sa.Integer(), nullable=True),
    sa.Column('runs', sa.Integer(), nullable=True),
    sa.Column('rbi', sa.Integer(), nullable=True),
    sa.Column('bb', sa.Integer(), nullable=True),
    sa.Column('ibb', sa.Integer(), nullable=True),
    sa.Column('so', sa.Integer(), nullable=True),
    sa.Column('hbp', sa.Integer(), nullable=True),
    sa.Column('sb', sa.Integer(), nullable=True),
    sa.Column('cs', sa.Integer(), nullable=True),
    sa.Column('sac_flies', sa.Integer(), nullable=True),
    sa.Column('sac_bunts', sa.Integer(), nullable=True),
    sa.Column('gidp', sa.Integer(), nullable=True),
    sa.Column('total_bases', sa.Integer(), nullable=True),
    sa.Column('left_on_base', sa.Integer(), nullable=True),
    sa.Column('games_started', sa.Integer(), nullable=True),
    sa.Column('outs_pitched', sa.Integer(), nullable=True),
    sa.Column('batters_faced', sa.Integer(), nullable=True),
    sa.Column('hits_allowed', sa.Integer(), nullable=True),
    sa.Column('runs_allowed', sa.Integer(), nullable=True),
    sa.Column('earned_runs', sa.Integer(), nullable=True),
    sa.Column('bb_allowed', sa.Integer(), nullable=True),
    sa.Column('ibb_allowed', sa.Integer(), nullable=True),
    sa.Column('so_pitched', sa.Integer(), nullable=True),
    sa.Column('hr_allowed', sa.Integer(), nullable=True),
    sa.Column('hbp_allowed', sa.Integer(), nullable=True),
    sa.Column('pitches_thrown', sa.Integer(), nullable=True),
    sa.Column('strikes_thrown', sa.Integer(), nullable=True),
    sa.Column('ground_outs_pitched', sa.Integer(), nullable=True),
    sa.Column('air_outs_pitched', sa.Integer(), nullable=True),
    sa.Column('inherited_runners', sa.Integer(), nullable=True),
    sa.Column('inherited_runners_scored', sa.Integer(), nullable=True),
    sa.Column('wild_pitches', sa.Integer(), nullable=True),
    sa.Column('balks', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('knowledge_time', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('batter','pitcher')", name='ck_pgs_role'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['opponent_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_id', 'role', name='uq_player_game_role')
    )
    op.create_index('ix_pgs_player_role_date', 'player_game_stats', ['player_id', 'role', 'game_date_utc'], unique=False)
    op.create_index('ix_pgs_starter', 'player_game_stats', ['player_id', 'is_starter', 'game_date_utc'], unique=False)
    op.create_index('ix_pgs_team_date', 'player_game_stats', ['team_id', 'game_date_utc'], unique=False)
    op.create_index('ix_pgs_team_role_starter_date', 'player_game_stats', ['team_id', 'role', 'is_starter', 'game_date_utc'], unique=False)
    op.create_index(op.f('ix_player_game_stats_knowledge_time'), 'player_game_stats', ['knowledge_time'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('home_win_prob', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('away_win_prob', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('home_win_prob_uncalibrated', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('projected_home_runs', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('projected_away_runs', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('projected_home_runs_low', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('projected_home_runs_high', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('projected_away_runs_low', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('projected_away_runs_high', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fair_home_moneyline', sa.Integer(), nullable=True),
    sa.Column('fair_away_moneyline', sa.Integer(), nullable=True),
    sa.Column('market_home_prob', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('market_edge', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('confidence_label', sa.String(length=24), nullable=False),
    sa.Column('recommendation', sa.String(length=32), nullable=False),
    sa.Column('model_agreement', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('data_completeness', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('missing_data', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feature_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('component_probs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('superseded_by', sa.BigInteger(), nullable=True),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.CheckConstraint('abs(home_win_prob + away_win_prob - 1) < 0.000001', name='ck_pred_probs_sum_to_one'),
    sa.CheckConstraint('home_win_prob > 0 AND home_win_prob < 1', name='ck_pred_prob_range'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['superseded_by'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'model_version_id', 'as_of', name='uq_prediction_asof')
    )
    op.create_index('ix_pred_created', 'predictions', ['created_at'], unique=False)
    op.create_index('ix_pred_game', 'predictions', ['game_id'], unique=False)
    op.create_index('uq_prediction_latest', 'predictions', ['game_id', 'model_version_id'], unique=True, postgresql_where=sa.text('is_latest IS true'))
    op.create_table('starting_pitcher_projections',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('pitcher_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('expected_innings', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('expected_pitch_count', sa.Integer(), nullable=True),
    sa.Column('days_rest', sa.Integer(), nullable=True),
    sa.Column('is_estimated', sa.Boolean(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_name', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('knowledge_time', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('CONFIRMED','PROBABLE','PROJECTED','UNKNOWN')", name='ck_spp_status'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['pitcher_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'team_id', 'as_of', name='uq_sp_projection')
    )
    op.create_index('ix_spp_game', 'starting_pitcher_projections', ['game_id'], unique=False)
    op.create_index(op.f('ix_starting_pitcher_projections_knowledge_time'), 'starting_pitcher_projections', ['knowledge_time'], unique=False)
    op.create_table('team_game_stats',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('opponent_team_id', sa.Integer(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('game_date_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('runs', sa.Integer(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('doubles', sa.Integer(), nullable=True),
    sa.Column('triples', sa.Integer(), nullable=True),
    sa.Column('home_runs', sa.Integer(), nullable=True),
    sa.Column('walks', sa.Integer(), nullable=True),
    sa.Column('intentional_walks', sa.Integer(), nullable=True),
    sa.Column('strikeouts', sa.Integer(), nullable=True),
    sa.Column('hit_by_pitch', sa.Integer(), nullable=True),
    sa.Column('stolen_bases', sa.Integer(), nullable=True),
    sa.Column('caught_stealing', sa.Integer(), nullable=True),
    sa.Column('left_on_base', sa.Integer(), nullable=True),
    sa.Column('at_bats', sa.Integer(), nullable=True),
    sa.Column('plate_appearances', sa.Integer(), nullable=True),
    sa.Column('total_bases', sa.Integer(), nullable=True),
    sa.Column('sac_flies', sa.Integer(), nullable=True),
    sa.Column('sac_bunts', sa.Integer(), nullable=True),
    sa.Column('gidp', sa.Integer(), nullable=True),
    sa.Column('runs_allowed', sa.Integer(), nullable=True),
    sa.Column('earned_runs_allowed', sa.Integer(), nullable=True),
    sa.Column('hits_allowed', sa.Integer(), nullable=True),
    sa.Column('walks_allowed', sa.Integer(), nullable=True),
    sa.Column('strikeouts_pitched', sa.Integer(), nullable=True),
    sa.Column('home_runs_allowed', sa.Integer(), nullable=True),
    sa.Column('outs_pitched', sa.Integer(), nullable=True),
    sa.Column('batters_faced', sa.Integer(), nullable=True),
    sa.Column('pitches_thrown', sa.Integer(), nullable=True),
    sa.Column('strikes_thrown', sa.Integer(), nullable=True),
    sa.Column('ground_outs_pitched', sa.Integer(), nullable=True),
    sa.Column('air_outs_pitched', sa.Integer(), nullable=True),
    sa.Column('errors', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('knowledge_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['opponent_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'team_id', name='uq_team_game')
    )
    op.create_index(op.f('ix_team_game_stats_knowledge_time'), 'team_game_stats', ['knowledge_time'], unique=False)
    op.create_index('ix_tgs_team_date', 'team_game_stats', ['team_id', 'game_date_utc'], unique=False)
    op.create_table('weather',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('observation_type', sa.String(length=16), nullable=False),
    sa.Column('valid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('temperature_f', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('feels_like_f', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('wind_speed_mph', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('wind_direction_deg', sa.Integer(), nullable=True),
    sa.Column('wind_direction_text', sa.Text(), nullable=True),
    sa.Column('wind_field_relative', sa.Text(), nullable=True),
    sa.Column('humidity_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pressure_mb', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('precipitation_prob', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('precipitation_mm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('air_density_kg_m3', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('roof_status', sa.Text(), nullable=True),
    sa.Column('is_estimated', sa.Boolean(), nullable=False),
    sa.Column('source_name', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('knowledge_time', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("observation_type IN ('FORECAST','OBSERVED')", name='ck_weather_obs_type'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['ballparks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_weather_game', 'weather', ['game_id', 'observation_type'], unique=False)
    op.create_index(op.f('ix_weather_knowledge_time'), 'weather', ['knowledge_time'], unique=False)
    op.create_table('batted_ball_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('pitch_id', sa.BigInteger(), nullable=True),
    sa.Column('batter_id', sa.Integer(), nullable=False),
    sa.Column('pitcher_id', sa.Integer(), nullable=False),
    sa.Column('launch_speed', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('launch_angle', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('hit_distance', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('is_barrel', sa.Boolean(), nullable=True),
    sa.Column('is_hard_hit', sa.Boolean(), nullable=True),
    sa.Column('bb_type', sa.Text(), nullable=True),
    sa.Column('estimated_woba', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('estimated_ba', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('source_name', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('knowledge_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batter_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], ),
    sa.ForeignKeyConstraint(['pitcher_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batted_ball_events_knowledge_time'), 'batted_ball_events', ['knowledge_time'], unique=False)
    op.create_index('ix_bbe_batter', 'batted_ball_events', ['batter_id', 'game_id'], unique=False)
    op.create_index('ix_bbe_pitcher', 'batted_ball_events', ['pitcher_id', 'game_id'], unique=False)
    op.create_table('prediction_explanations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('prediction_id', sa.BigInteger(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('feature_key', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('favors', sa.String(length=1), nullable=False),
    sa.Column('contribution_pp', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('feature_value', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('feature_display', sa.Text(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('is_estimated', sa.Boolean(), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.CheckConstraint("favors IN ('H','A')", name='ck_pexp_favors'),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pexp_prediction', 'prediction_explanations', ['prediction_id', 'rank'], unique=False)
    op.create_table('simulation_results',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('prediction_id', sa.BigInteger(), nullable=False),
    sa.Column('n_simulations', sa.Integer(), nullable=False),
    sa.Column('home_win_pct', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('away_win_pct', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('mean_home_runs', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('mean_away_runs', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('run_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('score_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extra_innings_prob', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('one_run_prob', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('upset_prob', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('seed', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulation_results')
    op.drop_index('ix_pexp_prediction', table_name='prediction_explanations')
    op.drop_table('prediction_explanations')
    op.drop_index('ix_bbe_pitcher', table_name='batted_ball_events')
    op.drop_index('ix_bbe_batter', table_name='batted_ball_events')
    op.drop_index(op.f('ix_batted_ball_events_knowledge_time'), table_name='batted_ball_events')
    op.drop_table('batted_ball_events')
    op.drop_index(op.f('ix_weather_knowledge_time'), table_name='weather')
    op.drop_index('ix_weather_game', table_name='weather')
    op.drop_table('weather')
    op.drop_index('ix_tgs_team_date', table_name='team_game_stats')
    op.drop_index(op.f('ix_team_game_stats_knowledge_time'), table_name='team_game_stats')
    op.drop_table('team_game_stats')
    op.drop_index(op.f('ix_starting_pitcher_projections_knowledge_time'), table_name='starting_pitcher_projections')
    op.drop_index('ix_spp_game', table_name='starting_pitcher_projections')
    op.drop_table('starting_pitcher_projections')
    op.drop_index('uq_prediction_latest', table_name='predictions', postgresql_where=sa.text('is_latest IS true'))
    op.drop_index('ix_pred_game', table_name='predictions')
    op.drop_index('ix_pred_created', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_player_game_stats_knowledge_time'), table_name='player_game_stats')
    op.drop_index('ix_pgs_team_role_starter_date', table_name='player_game_stats')
    op.drop_index('ix_pgs_team_date', table_name='player_game_stats')
    op.drop_index('ix_pgs_starter', table_name='player_game_stats')
    op.drop_index('ix_pgs_player_role_date', table_name='player_game_stats')
    op.drop_table('player_game_stats')
    op.drop_index('ix_pitches_pitcher', table_name='pitches')
    op.drop_index(op.f('ix_pitches_knowledge_time'), table_name='pitches')
    op.drop_index('ix_pitches_game', table_name='pitches')
    op.drop_index('ix_pitches_batter', table_name='pitches')
    op.drop_table('pitches')
    op.drop_index(op.f('ix_odds_snapshots_knowledge_time'), table_name='odds_snapshots')
    op.drop_index('ix_odds_game_time', table_name='odds_snapshots')
    op.drop_table('odds_snapshots')
    op.drop_index('ix_mf_game', table_name='model_features')
    op.drop_index('ix_mf_features', table_name='model_features', postgresql_using='gin')
    op.drop_table('model_features')
    op.drop_index(op.f('ix_lineups_knowledge_time'), table_name='lineups')
    op.drop_index('ix_lineups_game_team', table_name='lineups')
    op.drop_table('lineups')
    op.drop_index(op.f('ix_game_officials_knowledge_time'), table_name='game_officials')
    op.drop_table('game_officials')
    op.drop_index(op.f('ix_bullpen_availability_knowledge_time'), table_name='bullpen_availability')
    op.drop_table('bullpen_availability')
    op.drop_index('ix_btp_run', table_name='backtest_predictions')
    op.drop_table('backtest_predictions')
    op.drop_index('ix_rosters_team_season', table_name='rosters')
    op.drop_index('ix_rosters_player', table_name='rosters')
    op.drop_index(op.f('ix_rosters_knowledge_time'), table_name='rosters')
    op.drop_table('rosters')
    op.drop_index('ix_injuries_player_effective', table_name='injuries')
    op.drop_index(op.f('ix_injuries_knowledge_time'), table_name='injuries')
    op.drop_table('injuries')
    op.drop_index('ix_games_season_type', table_name='games')
    op.drop_index('ix_games_official_date', table_name='games')
    op.drop_index(op.f('ix_games_knowledge_time'), table_name='games')
    op.drop_index('ix_games_home_date', table_name='games')
    op.drop_index('ix_games_final_date', table_name='games')
    op.drop_index('ix_games_away_date', table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_teams_knowledge_time'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_park_factors_knowledge_time'), table_name='park_factors')
    op.drop_table('park_factors')
    op.drop_index('ix_btr_run_slice', table_name='backtest_results')
    op.drop_table('backtest_results')
    op.drop_index('ix_raw_retrieved', table_name='raw_source_payloads')
    op.drop_table('raw_source_payloads')
    op.drop_index(op.f('ix_players_knowledge_time'), table_name='players')
    op.drop_table('players')
    op.drop_index('uq_model_version_active', table_name='model_versions', postgresql_where=sa.text('is_active IS true'))
    op.drop_table('model_versions')
    op.drop_index('ix_job_runs_name_started', table_name='job_runs')
    op.drop_table('job_runs')
    op.drop_table('data_source_status')
    op.drop_index(op.f('ix_ballparks_knowledge_time'), table_name='ballparks')
    op.drop_table('ballparks')
    op.drop_table('backtest_runs')
    # ### end Alembic commands ###
