"""phase 2a statcast columns

Revision ID: e37fd67a9dfd
Revises: 0001_initial
Create Date: 2026-08-01 15:07:19.459853
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'e37fd67a9dfd'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batted_ball_events', sa.Column('at_bat_index', sa.Integer(), nullable=True))
    op.add_column('batted_ball_events', sa.Column('pitch_number', sa.Integer(), nullable=True))
    op.add_column('batted_ball_events', sa.Column('launch_speed_angle', sa.SmallInteger(), nullable=True))
    op.add_column('batted_ball_events', sa.Column('estimated_slg', sa.Numeric(precision=5, scale=4), nullable=True))
    op.add_column('batted_ball_events', sa.Column('woba_value', sa.Numeric(precision=5, scale=4), nullable=True))
    op.add_column('batted_ball_events', sa.Column('woba_denom', sa.SmallInteger(), nullable=True))
    op.add_column('batted_ball_events', sa.Column('spray_angle', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('batted_ball_events', sa.Column('field_direction', sa.String(length=4), nullable=True))
    op.drop_index('ix_bbe_batter', table_name='batted_ball_events')
    op.drop_index('ix_bbe_pitcher', table_name='batted_ball_events')
    op.create_index('ix_bbe_batter_known', 'batted_ball_events', ['batter_id', 'knowledge_time'], unique=False)
    op.create_index('ix_bbe_game', 'batted_ball_events', ['game_id'], unique=False)
    op.create_index('ix_bbe_pitcher_known', 'batted_ball_events', ['pitcher_id', 'knowledge_time'], unique=False)
    op.create_unique_constraint('uq_bbe', 'batted_ball_events', ['game_id', 'at_bat_index', 'pitch_number'])
    op.add_column('pitches', sa.Column('pitch_name', sa.Text(), nullable=True))
    op.add_column('pitches', sa.Column('effective_speed', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('pitches', sa.Column('spin_axis', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('batter_stands', sa.String(length=1), nullable=True))
    op.add_column('pitches', sa.Column('pitcher_throws', sa.String(length=1), nullable=True))
    op.add_column('pitches', sa.Column('is_pitch', sa.Boolean(), nullable=True))
    op.add_column('pitches', sa.Column('is_swing', sa.Boolean(), nullable=True))
    op.add_column('pitches', sa.Column('is_whiff', sa.Boolean(), nullable=True))
    op.add_column('pitches', sa.Column('is_called_strike', sa.Boolean(), nullable=True))
    op.add_column('pitches', sa.Column('is_in_zone', sa.Boolean(), nullable=True))
    op.add_column('pitches', sa.Column('times_through_order', sa.SmallInteger(), nullable=True))
    op.add_column('pitches', sa.Column('pitcher_days_since_prev', sa.SmallInteger(), nullable=True))
    op.add_column('pitches', sa.Column('bat_speed', sa.Numeric(precision=4, scale=1), nullable=True))
    op.add_column('pitches', sa.Column('swing_length', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('pitches', sa.Column('pa_event', sa.Text(), nullable=True))
    op.add_column('pitches', sa.Column('woba_value', sa.Numeric(precision=5, scale=4), nullable=True))
    op.add_column('pitches', sa.Column('woba_denom', sa.SmallInteger(), nullable=True))
    op.drop_index('ix_pitches_batter', table_name='pitches')
    op.drop_index('ix_pitches_pitcher', table_name='pitches')
    op.create_index('ix_pitches_batter_known', 'pitches', ['batter_id', 'knowledge_time'], unique=False)
    op.create_index('ix_pitches_pitcher_known', 'pitches', ['pitcher_id', 'knowledge_time'], unique=False)
    op.create_unique_constraint('uq_pitch', 'pitches', ['game_id', 'at_bat_index', 'pitch_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_pitch', 'pitches', type_='unique')
    op.drop_index('ix_pitches_pitcher_known', table_name='pitches')
    op.drop_index('ix_pitches_batter_known', table_name='pitches')
    op.create_index('ix_pitches_pitcher', 'pitches', ['pitcher_id', 'game_id'], unique=False)
    op.create_index('ix_pitches_batter', 'pitches', ['batter_id', 'game_id'], unique=False)
    op.drop_column('pitches', 'woba_denom')
    op.drop_column('pitches', 'woba_value')
    op.drop_column('pitches', 'pa_event')
    op.drop_column('pitches', 'swing_length')
    op.drop_column('pitches', 'bat_speed')
    op.drop_column('pitches', 'pitcher_days_since_prev')
    op.drop_column('pitches', 'times_through_order')
    op.drop_column('pitches', 'is_in_zone')
    op.drop_column('pitches', 'is_called_strike')
    op.drop_column('pitches', 'is_whiff')
    op.drop_column('pitches', 'is_swing')
    op.drop_column('pitches', 'is_pitch')
    op.drop_column('pitches', 'pitcher_throws')
    op.drop_column('pitches', 'batter_stands')
    op.drop_column('pitches', 'spin_axis')
    op.drop_column('pitches', 'effective_speed')
    op.drop_column('pitches', 'pitch_name')
    op.drop_constraint('uq_bbe', 'batted_ball_events', type_='unique')
    op.drop_index('ix_bbe_pitcher_known', table_name='batted_ball_events')
    op.drop_index('ix_bbe_game', table_name='batted_ball_events')
    op.drop_index('ix_bbe_batter_known', table_name='batted_ball_events')
    op.create_index('ix_bbe_pitcher', 'batted_ball_events', ['pitcher_id', 'game_id'], unique=False)
    op.create_index('ix_bbe_batter', 'batted_ball_events', ['batter_id', 'game_id'], unique=False)
    op.drop_column('batted_ball_events', 'field_direction')
    op.drop_column('batted_ball_events', 'spray_angle')
    op.drop_column('batted_ball_events', 'woba_denom')
    op.drop_column('batted_ball_events', 'woba_value')
    op.drop_column('batted_ball_events', 'estimated_slg')
    op.drop_column('batted_ball_events', 'launch_speed_angle')
    op.drop_column('batted_ball_events', 'pitch_number')
    op.drop_column('batted_ball_events', 'at_bat_index')
    # ### end Alembic commands ###
